-- =====================================================================
-- AI Revenue Recovery Agent — Supabase (PostgreSQL) Schema
-- Run this in the Supabase SQL Editor (Project -> SQL Editor -> New query)
-- =====================================================================

-- Clean slate (safe to re-run during hackathon iteration)
drop table if exists ai_audit_logs cascade;
drop table if exists transactions cascade;
drop table if exists users cascade;

-- ---------------------------------------------------------------------
-- 1. USERS
-- ---------------------------------------------------------------------
create table users (
    user_id     uuid primary key default gen_random_uuid(),
    name        text not null,
    email       text unique not null,
    phone       text,
    created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 2. TRANSACTIONS
-- ---------------------------------------------------------------------
create table transactions (
    txn_id      uuid primary key default gen_random_uuid(),
    user_id     uuid not null references users(user_id) on delete cascade,
    amount      numeric(12, 2) not null,
    status      text not null check (status in ('failed', 'abandoned', 'recovered', 'pending')),
    error_code  text,                     -- e.g. INSUFFICIENT_FUNDS, GATEWAY_TIMEOUT, CARD_DECLINED
    created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- 3. AI_AUDIT_LOGS
-- ---------------------------------------------------------------------
create table ai_audit_logs (
    log_id              uuid primary key default gen_random_uuid(),
    txn_id              uuid not null references transactions(txn_id) on delete cascade,
    root_cause_diagnosed text,            -- AI's diagnosis, e.g. "Insufficient Funds"
    action_taken        text not null,    -- e.g. SEND_EMI_LINK, SEND_RETRY_LINK, HALT_MAX_ATTEMPTS, HALT_PROMISE_TO_PAY
    message_sent         text,            -- personalized recovery message generated by the LLM
    money_recovered      boolean not null default false,
    status               text not null default 'promise_pending'
                          check (status in ('promise_pending', 'promised_to_pay', 'recovered', 'halted', 'failed')),
    timestamp            timestamptz not null default now()
);

-- ---------------------------------------------------------------------
-- Helpful indexes for the dashboard queries
-- ---------------------------------------------------------------------
create index idx_transactions_user_id on transactions(user_id);
create index idx_audit_logs_txn_id on ai_audit_logs(txn_id);
create index idx_audit_logs_timestamp on ai_audit_logs(timestamp desc);

-- ---------------------------------------------------------------------
-- Seed data (optional — lets you demo the dashboard immediately)
-- ---------------------------------------------------------------------
insert into users (name, email, phone) values
    ('Aarav Sharma', 'aarav.sharma@example.com', '+919810012345'),
    ('Priya Nair', 'priya.nair@example.com', '+919820098765')
returning user_id;
